language: python
python: 3.8

install:
    - pip install .
    - pip install codecov

script:
    - export VERSION=$(git describe --tags --abbrev=0)
    - sed -i "s/0.0.1/${VERSION}/" ./pyTuplingUtils/__init__.py
    - make unittest
    - make integrationtest

after_success:
    - codecov

deploy:
    provider: pypi
    edge: true
    user: __token__
    password:
        secure: eMoLN9ychc0JlHUVXrxiJhTEsqXUri66dgocWc4qb90BZbB1l0pDI5PZOybxv69Tj/zs7dVCWKiELSlfl0vPJ65iVzzYRHEa7HK8KR4JzotBDHnxcgJFkMy9KVtlDTmsOwPKKfu2n5iENxAp36lPA46KTQuLrFrAu1ocLNzlUQYgGh94mWWlogEIDCU8PiT+cvt9WMkzM14xT6OIWCegCW4D/4Ejp9xxyABAMZRtXIfqTqewkIjHhaU1RyOdMsRw1hMe4Cy/R/Op4oDq3gVSd6yPlAM5IpWw2ffzsa29QUftCMFgn5ttuOugoyGYrFfwc1wXJQ91ekGFCUeKPm4PgaNtitdEQA1CRgm8jWF2IBPu+F2Wh0I5HwtaxQahNXBYEeA00c6yKIG2FvLKxmULmj7O9ZleTLt0nQ1TgOVAGooh5KDvRd9uuRl4x7RKTaHXpo2y4wc1aZi34dl5JEN0IwGJ1+pWf6HwE7gFQajIphLjwmBcTAck30sToJr+HmtjMgZCl4PUS2qqK8QzvPoGS9BVtCUvT0CSBozbG/cwvYxWAV15BvHXlln74pkYTjMQZ4KsaaMYVKvMBdNoU8y9Os/DJarYxB3ncl5diYuV0aoBcrQ2iX4c+lGsjPXLHMGISqaz/rP+AiY+fNtf8f1ltIEpLjRSeY59dpNXmNvyUKs=
    on:
        tags: true
