language: python
dist: bionic
python: 3.8

install:
    - pip install -r ./requirements.txt
    - pip install codecov

script:
    - export PYTUPLINGUTILS_VERSION=$(git describe --tags --abbrev=0)
    - echo 'version = "'"${PYTUPLINGUTILS_VERSION}"'"' >> ./pyTuplingUtils/__init__.py
    - make test

after_success:
    - codecov

deploy:
    provider: pypi
    user: yipengsun
    skip_cleanup: true
    on:
        tags: true
    password:
        secure: cX4lXWAjSz4TpWu2M8/KlXya4dajJnFn6Vu/FIFFh97CD6jHWjARmtqMYun2pfBk/kgxWalrm/fNqLsp+KW1bpIGdz7h7sz9x5UkrcZ0oGObst6rVsXR6UNpbcWhwrmiPA7WTRnygDy3zlQ59zHDMl9HE0tpPNzOtqNuc4nPk3jreSJ9CdwAgVsWM7jjc7H4iVbGGAnSTVlS4iNIqUX7MO9nWMAbInXW1xeczOG6tL/3frc6wymUZBpZLlBuEytRSpFQDn23Yh0TbGWFLbIyYoc02w+8e2WbKMr1FJiniKOZxw27dliHn4i2+dZ/Bdk4s6/0r3yEhrYcrTI32pheD6PlaoSQ7KM+vA94dSQ1HSFsnoll8BjmUInDrxVi3dO462nfYsvZIPqdus6Mloe+MU1iuGJqRO9Trgv+cVZ2H+hOBzfcDAFmmJjKYeY0Ltt1mMwxAH0uFZzayheXuIYXgtaqSZAXYEyy+lkgjG4IkvuDWAjc5hzCmrWP5KftshB/YXYgb7Ikg4grw6LyuP9tQQQf6fu6OeX5firmQnU4rC9H5BHtjEsGhzvJfAIDs2dBoymO/SSZeM8ALT60QswTgHzJ+5cUnSvc+BdbfVg0QOs8HBPbOd5rl+WELxqf+J0hGTQsjr/UNYHFA9BbNVg5mrL9/Zrn5nMJD4wxljKiqNc=
